[project]
name = "airflow-pinecone-embeddings-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pinecone>=7.3.0",
    "sentence-transformers>=5.1.2",
]
